### ISSUE TITLE
getitifixed dependency to this project is causing an error because since version 0.14.0 geoalchemy2 doesn't allow the "management" option in Geometry() function

### ISSUE THREAD

**Issue by nicolas-sitylb** [camptocamp/c2cgeoform#860]
Hi,

when one installs the `c2cgeoform` package, even with its lowest version number, it will install `geoalchemy` > `0.18.4`:

```sh
$ pip install c2cgeoform==2.1.17
Collecting c2cgeoform==2.1.17
  Downloading c2cgeoform-2.1.17-py2.py3-none-any.whl (267 kB)
     |████████████████████████████████| 267 kB 3.0 MB/s
Collecting geoalchemy2>=0.4.0
  Using cached geoalchemy2-0.18.4-py3-none-any.whl (81 kB)
```
indeed:
https://github.com/camptocamp/c2cgeoform/blob/99ea18ba2ef8bb94432b15c2880e47f8b670a7fe/pyproject.toml#L38

This is fine, but since `geoalchemy2` version ` 0.14.0`, the  `geoalchemy2.Geometry()` function doesn't support the `management` option anymore:

- worked in `0.13.3`:
```py
Python 3.10.2 (main, Jan 18 2022, 20:00:03) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import geoalchemy2
>>> geoalchemy2.__version__
'0.13.3'
>>> geoalchemy2.Geometry('Point',4326,management=True)
Geometry(geometry_type='POINT', srid=4326, management=True, from_text='ST_GeomFromEWKT', name='geometry')
```
- and since `0.14.0`, an error is raised:
```py
Python 3.10.2 (main, Jan 18 2022, 20:00:03) [GCC 10.2.1 20210110] on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import geoalchemy2
>>> geoalchemy2.__version__
'0.14.0'
>>> geoalchemy2.Geometry('Point',4326,management=True)
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
TypeError: _GISType.__init__() got an unexpected keyword argument 'management'
```

because of that, the [`getitfixed`](https://github.com/camptocamp/getitfixed/) project, [as published on pypi](https://pypi.org/project/getitfixed/), which depends on `c2cgeoform` will not work because it makes use of the `management` option in `geoalchemy2.Geometry()` function at some places in the code, e.g. [here](https://github.com/camptocamp/getitfixed/blob/623f9bcdce333b10676d967a4e5a28f3fd2bed5c/getitfixed/models/getitfixed.py#L255), or [there](https://github.com/camptocamp/getitfixed/blob/623f9bcdce333b10676d967a4e5a28f3fd2bed5c/getitfixed/alembic/versions/0b12402a098e_first_migration.py#L72). Therefore, because of the version dependency coded [here](https://github.com/camptocamp/getitfixed/blob/623f9bcdce333b10676d967a4e5a28f3fd2bed5c/requirements.txt#L3), one will encounter the same error as described above 💥

This seriously affects the `c2cgeoportal` upgrade to 2.9+ for those who use `getitfixed` in their project:

```sh
geoportal-1  | Traceback (most recent call last):
geoportal-1  |   File "/venv/lib/python3.12/site-packages/gunicorn/arbiter.py", line 608, in spawn_worker
geoportal-1  |     worker.init_process()
geoportal-1  |   File "/venv/lib/python3.12/site-packages/gunicorn/workers/gthread.py", line 94, in init_process
geoportal-1  |     super().init_process()
geoportal-1  |   File "/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 135, in init_process
geoportal-1  |     self.load_wsgi()
geoportal-1  |   File "/venv/lib/python3.12/site-packages/gunicorn/workers/base.py", line 147, in load_wsgi
geoportal-1  |     self.wsgi = self.app.wsgi()
geoportal-1  |                 ^^^^^^^^^^^^^^^
geoportal-1  |   File "/venv/lib/python3.12/site-packages/gunicorn/app/base.py", line 66, in wsgi
geoportal-1  |     self.callable = self.load()
geoportal-1  |                     ^^^^^^^^^^^
geoportal-1  |   File "/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 55, in load
geoportal-1  |     return self.load_pasteapp()
geoportal-1  |            ^^^^^^^^^^^^^^^^^^^^
geoportal-1  |   File "/venv/lib/python3.12/site-packages/gunicorn/app/wsgiapp.py", line 51, in load_pasteapp
geoportal-1  |     return get_wsgi_app(self.app_uri, defaults=self.cfg.paste_global_conf)
geoportal-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
geoportal-1  |   File "/venv/lib/python3.12/site-packages/gunicorn/app/pasterapp.py", line 18, in get_wsgi_app
geoportal-1  |     return loadapp(
geoportal-1  |            ^^^^^^^^
geoportal-1  |   File "/venv/lib/python3.12/site-packages/paste/deploy/loadwsgi.py", line 246, in loadapp
geoportal-1  |     return loadobj(APP, uri, name=name, **kw)
geoportal-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
geoportal-1  |   File "/venv/lib/python3.12/site-packages/paste/deploy/loadwsgi.py", line 271, in loadobj
geoportal-1  |     return context.create()
geoportal-1  |            ^^^^^^^^^^^^^^^^
geoportal-1  |   File "/venv/lib/python3.12/site-packages/paste/deploy/loadwsgi.py", line 738, in create
geoportal-1  |     return self.object_type.invoke(self)
geoportal-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
geoportal-1  |   File "/venv/lib/python3.12/site-packages/paste/deploy/loadwsgi.py", line 198, in invoke
geoportal-1  |     app = context.app_context.create()
geoportal-1  |           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
geoportal-1  |   File "/venv/lib/python3.12/site-packages/paste/deploy/loadwsgi.py", line 738, in create
geoportal-1  |     return self.object_type.invoke(self)
geoportal-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
geoportal-1  |   File "/venv/lib/python3.12/site-packages/paste/deploy/loadwsgi.py", line 226, in invoke
geoportal-1  |     filtered = context.next_context.create()
geoportal-1  |                ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
geoportal-1  |   File "/venv/lib/python3.12/site-packages/paste/deploy/loadwsgi.py", line 738, in create
geoportal-1  |     return self.object_type.invoke(self)
geoportal-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
geoportal-1  |   File "/venv/lib/python3.12/site-packages/paste/deploy/loadwsgi.py", line 136, in invoke
geoportal-1  |     return fix_call(context.object, context.global_conf, **context.local_conf)
geoportal-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
geoportal-1  |   File "/venv/lib/python3.12/site-packages/paste/deploy/util.py", line 64, in fix_call
geoportal-1  |     raise exc_info[1] from None
geoportal-1  |   File "/venv/lib/python3.12/site-packages/paste/deploy/util.py", line 61, in fix_call
geoportal-1  |     val = callable(*args, **kw)
geoportal-1  |           ^^^^^^^^^^^^^^^^^^^^^
geoportal-1  |   File "/app/myinstance_c2cgeoportal_geoportal/__init__.py", line 44, in main
geoportal-1  |     config.include("c2cgeoportal_geoportal")
geoportal-1  |   File "/venv/lib/python3.12/site-packages/pyramid/config/__init__.py", line 666, in include
geoportal-1  |     c(configurator)
geoportal-1  |   File "/opt/c2cgeoportal/geoportal/c2cgeoportal_geoportal/__init__.py", line 863, in includeme
geoportal-1  |     add_getitfixed(config)
geoportal-1  |   File "/opt/c2cgeoportal/geoportal/c2cgeoportal_geoportal/__init__.py", line 282, in add_getitfixed
geoportal-1  |     config.include("getitfixed")
geoportal-1  |   File "/venv/lib/python3.12/site-packages/pyramid/config/__init__.py", line 666, in include
geoportal-1  |     c(configurator)
geoportal-1  |   File "/venv/lib/python3.12/site-packages/getitfixed/__init__.py", line 42, in includeme
geoportal-1  |     config.include(".routes")
geoportal-1  |   File "/venv/lib/python3.12/site-packages/pyramid/config/__init__.py", line 632, in include
geoportal-1  |     c = self.maybe_dotted(callable)
geoportal-1  |         ^^^^^^^^^^^^^^^^^^^^^^^^^^^
geoportal-1  |   File "/venv/lib/python3.12/site-packages/pyramid/config/__init__.py", line 740, in maybe_dotted
geoportal-1  |     return self.name_resolver.maybe_resolve(dotted)
geoportal-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
geoportal-1  |   File "/venv/lib/python3.12/site-packages/pyramid/path.py", line 327, in maybe_resolve
geoportal-1  |     return self._resolve(dotted, package)
geoportal-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
geoportal-1  |   File "/venv/lib/python3.12/site-packages/pyramid/path.py", line 334, in _resolve
geoportal-1  |     return self._zope_dottedname_style(dotted, package)
geoportal-1  |            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
geoportal-1  |   File "/venv/lib/python3.12/site-packages/pyramid/path.py", line 389, in _zope_dottedname_style
geoportal-1  |     __import__(used)
geoportal-1  |   File "/venv/lib/python3.12/site-packages/getitfixed/routes.py", line 2, in <module>
geoportal-1  |     from getitfixed.models.getitfixed import Event, Issue
geoportal-1  |   File "/venv/lib/python3.12/site-packages/getitfixed/models/__init__.py", line 8, in <module>
geoportal-1  |     from getitfixed.models.getitfixed import Base  # noqa
geoportal-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
geoportal-1  |   File "/venv/lib/python3.12/site-packages/getitfixed/models/getitfixed.py", line 223, in <module>
geoportal-1  |     class Issue(Base):
geoportal-1  |   File "/venv/lib/python3.12/site-packages/getitfixed/models/getitfixed.py", line 255, in Issue
geoportal-1  |     geoalchemy2.Geometry("POINT", 4326, management=True),
geoportal-1  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
geoportal-1  | TypeError: _GISType.__init__() got an unexpected keyword argument 'management'
geoportal-1  | Worker (pid:51) exited with code 3
```

What would you recommend to resolve this issue?

Many thanks! 🙏

**Comment by sbrunner** [comment]
Did you try the master branch?

**Comment by nicolas-sitylb** [comment]
Hello @sbrunner ;

we didn't test with the `master` branch and we don't necessarily want to, because we would like to focus on the [c2cgeoportal version 2.9.0](https://github.com/camptocamp/c2cgeoportal/releases/tag/2.9.0) for the migration of our production instance at the end. 

That's why I'm testing the specific 2.9.0 release where I met the described issue.
